python:
  - "2.7"

os:
  - linux

sudo: false
addons:
  apt:
    packages:
      - python-pip
      - python-virtualenv
      - libxslt1-dev
      - python2.7-dev
      - python-lxml

install:
  - "virtualenv /tmp/xml2rfc"
  - "/tmp/xml2rfc/bin/pip install xml2rfc"

script:
  - "PATH=/tmp/xml2rfc/bin:$PATH make"
